package com.yang.jaxws.service.impl.helloservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-23T11:34:29.903+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://impl.service.jaxws.yang.com/", name = "HelloServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloServiceImpl {

    @WebMethod
    @Action(input = "http://impl.service.jaxws.yang.com/HelloServiceImpl/sayHelloRequest", output = "http://impl.service.jaxws.yang.com/HelloServiceImpl/sayHelloResponse")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://impl.service.jaxws.yang.com/", className = "com.yang.jaxws.service.impl.helloservice.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://impl.service.jaxws.yang.com/", className = "com.yang.jaxws.service.impl.helloservice.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://impl.service.jaxws.yang.com/HelloServiceImpl/changeNameRequest", output = "http://impl.service.jaxws.yang.com/HelloServiceImpl/changeNameResponse")
    @RequestWrapper(localName = "changeName", targetNamespace = "http://impl.service.jaxws.yang.com/", className = "com.yang.jaxws.service.impl.helloservice.ChangeName")
    @ResponseWrapper(localName = "changeNameResponse", targetNamespace = "http://impl.service.jaxws.yang.com/", className = "com.yang.jaxws.service.impl.helloservice.ChangeNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.yang.jaxws.service.impl.helloservice.User changeName(
        @WebParam(name = "arg0", targetNamespace = "")
        com.yang.jaxws.service.impl.helloservice.User arg0
    );
}
